### ISSUE TITLE
Nightly broke profile creation

### ISSUE THREAD

**Issue by vladikoff** [vladikoff/fxa-dev-launcher#6]
I think Nightly with the new "nightly profile" thing broke `npm start` on this repo

**Comment by vbudhram** [comment]
@vladikoff Just got around to updating my test Firefox version to 67, and `npm start` does not work anymore. 

Looking through the code nothing obvious sticks out that would have caused this, any thoughts?

**Comment by vladikoff** [comment]
@vbudhram did you update to latest version `2.0.0`?

**Comment by dannycoates** [comment]
@vladikoff where is this magical `2.0.0`?

**Comment by vladikoff** [comment]
Oh sorry, thought it was this repo https://github.com/vladikoff/foxfire/releases/tag/v2.0.0

**Comment by vladikoff** [comment]
We might need to bump it here: https://github.com/vladikoff/fxa-dev-launcher/blob/master/package.json#L20

**Comment by vladikoff** [comment]
Seems to work for me! 

try with https://github.com/vladikoff/fxa-dev-launcher/pull/7

**Comment by dannycoates** [comment]
wfm, thanks @vladikoff!
